version: '3.8'

services:
  nexus-registry:
    image: 'sonatype/nexus3'
    ports:
      - '8081:8081'
    volumes:
      - npm-registry:/nexus-data

  bit-server:
    build:
      context: ./
      dockerfile: ./Docckefiles/bit-server.dockerfile
      args:
        SCOPE_PATH: /root/my-scope
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

volumes:
  npm-registry:
